### PR TITLE
Adapt new refactor

### PR DESCRIPTION
**Pull request by arichiardi**
This patch fixes a couple of glitches and tries to fix the rust tests.

Given that the font lock has somewhat changed from rust, I might need some help from @fredyr so that I can understand what has been removed in terms of keyword detection.

The path also introduces `Cask` so that now the tests can be executed with a simple:

```
(cask install - if first time)
cask exec ./run_tests.sh
```

### CODE REVIEW

**Comment by arichiardi** [comment]
@fredyr in particular tests like https://github.com/fredyr/reason-mode-fork/blob/6b53815a0405be1f364a082d22fe5c900409a01a/test/reason-test.el#L230 broke for some reason I am still investigating and I don't feel confident in releasing with these changes until we figure out what happened.

For helping you and myself out here, it use to be indented:

```
fun foo() => {
  switch blah {
    | Pattern => "dada"
    | Pattern2 => {
        hello()
      }
    | _ => "whatever"
  }
};
```

while with the current patch is:

```
fun foo() => {
  switch blah {
  | Pattern => "dada"
  | Pattern2 => {
  hello()
  }
  | _ => "whatever"
}
};
```

**Comment by fredyr** [comment]
Hi, I just got to looking at this a little bit. If I understand correctly, your commit that reverts things in indent fixes the test you referenced? At least it doesn't fail when I ran the test suite. 

Anyways, the background as to why I've started to change the behaviour of the indent is that it doesn't match what `refmt` outputs, which I think is what we should aim for.
Example, previous indent result:
```reason
fun foo() => {
  switch blah {
    | Pattern => "dada"
    | Pattern2 => {
        hello();
        "str"
      }
    | _ => "whatever"
  };
  ()
};
```
Same code run through `refmt`:

```reason
fun foo () => {
  switch blah {
  | Pattern => "dada"
  | Pattern2 =>
    hello ();
    "str"
  | _ => "whatever"
  };
  ()
};
```
Since `refmt` removes unnecessary parenthesis, I added some extra dummy statements in the blocks.

**Comment by arichiardi** [comment]
Yes you are right, reverting solves the test issues. I added a couple more, which are failing now (you can see by running this branch) of what I think some alignment should be for args. Still need to work on the solution...

But now I get it. I am torn on this one, because folks can hook refmt directly​ if they desire so.

I will need some input on this one 😀


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arichiardi** [comment]
Ok I will change the tests to reflect `refmt` then, I quickly inquired Discord and it seems like we need to support both and therefore it makes sense to have the same indentation.
Then I will try to re-revert aka reapply your changes and see what happens.

**Comment by arichiardi** [comment]
So @fredyr I gave the tests a better shape, according to `refmt` as you can see in the last commit.
You can also find them here: https://gist.github.com/arichiardi/3506ded7d9d796d2b53b53280a859cdb
The above file compiles fine so you can do `cat file | refmt`, I fixed the compilation errors in tests as well.

I reapplied your changes but there were still more failing tests than without. I did not have time to debug why. Only this one still happens:

```
fun foo() => {
  switch blah {
  | Pattern => "dada"
  | Pattern2 => {
  hello()
  }
  | _ => "whatever"
}
};
```

I would say, if you have time to work on a solution that is fitting these is better. If you don't, I will do it :smile: Whoever comes first wins :1st_place_medal: Also if you feel that some cases should be indented differently, point me to it and we'll discuss about it.

**Comment by fredyr** [comment]
Good job! I'm hoping to get to work on fixing these, but alas, family and work takes priority. I'll let you know when I dig in, so we don't do double work though.

**Pull request merged**
